name: Testes Automatizados Cypress

# 1. Quando deve ser executado?
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main # Roda quando alguém tentar fazer um Pull Request para a main
  schedule:
    - cron: '0 6 * * 1-5' # Roda sozinho de segunda a sexta, às 08h00 da manhã

# 2. O que ele deve fazer?
jobs:
  rodar-testes:
    runs-on: ubuntu-latest # Liga um computador Linux virtual na nuvem
    
    steps:
      - name: Pegar o código do projeto
        uses: actions/checkout@v4

      - name: Instalar tudo e rodar o Cypress
        uses: cypress-io/github-action@v6
        # Esse comando oficial do Cypress já instala o Node, 
        # dá 'npm install' nas dependências e roda 'npx cypress run'!
        
      - name: Salvar vídeos e screenshots (Evidências)
        uses: actions/upload-artifact@v4
        if: always() # Salva MESMO que o teste falhe!
        with:
          name: evidencias-cypress
          path: |
            cypress/videos
            cypress/screenshots
          retention-days: 7 # Guarda os arquivos por 7 dias para economizar espaço